apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  ports:
    - protocol: TCP
      name: nginx
      port: 9001
      targetPort: 80
      nodePort: 30001
    - protocol: TCP
      name: multitool
      port: 9002
      targetPort: 8080
      nodePort: 30002
    - protocol: TCP
      name: multitool-pod
      port: 8888
      targetPort: 8080
  selector:
    app: nginx-multitool
  type: NodePort